[package]
name = "dx_use_js_bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = "0.7.0-alpha.3"
dioxus-desktop = "0.7.0-alpha.3"
dioxus-signals = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-wasm-bindgen = "0.6"
uuid = { version = "1.8", optional = true }
chrono = { version = "0.4", features = ["serde"] }
once_cell = "1.19"
libc = { version = "0.2", optional = true }

# Web
wasm-bindgen = { version = "0.2", optional = true }
web-sys = { version = "0.3", optional = true }
js-sys = { version = "0.3", optional = true }

# Tauri (desktop)
tauri = { version = "2.7.0", optional = true }

[features]
default = []
web = ["wasm-bindgen", "web-sys", "js-sys"]
tauri = ["dep:tauri"]
android = ["dep:libc"]

[lib]
crate-type = ["cdylib", "rlib"]