[package]
name = "dx_use_js_bridge"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dioxus = { version = "0.7.0-alpha.3", features = ["web", "desktop"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
uuid = { version = "1.0", features = ["v4", "js"], optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.100"
serde-wasm-bindgen = "0.6.5"
web-sys = { version = "0.3.77", features = ["Window", "console"] }
js-sys = "0.3.77"

[features]
default = []
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
uuid = ["dep:uuid"]
