[package]
name = "dx_use_js_bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = "0.7.0-alpha.3"
dioxus-signals = "0.7.0-alpha.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-wasm-bindgen = "0.6"
once_cell = "1.19"
uuid = { version = "1.8", optional = true }
chrono = { version = "0.4", features = ["serde"] }

[target.'cfg(target_arch = "wasm")'.dependencies]

# Web
wasm-bindgen = { version = "0.2", optional = true }
web-sys = { version = "0.3", optional = true }
js-sys = { version = "0.3", optional = true }


[target.'cfg(target_os = "android")'.dependencies]

libc = { version = "0.2", optional = true }



[target.'cfg(not(any(target_arch = "wasm32", target_os = "android")))'.dependencies]
dioxus-desktop = "0.7.0-alpha.3"


[features]
default = []
web = ["wasm-bindgen", "web-sys", "js-sys"]
android = ["dep:libc"]

[lib]
crate-type = ["cdylib", "rlib"]
