[package]
name = "dx_use_js_bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = "0.7.0-alpha.3"
dioxus-signals = "0.7.0-alpha.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
once_cell = "1.19"
uuid = { version = "1.8", optional = true }
chrono = { version = "0.4", features = ["serde"] }

# Web - make these available for all targets but only used conditionally in code
wasm-bindgen = { version = "0.2", optional = false }
web-sys = { version = "0.3", optional = false }
js-sys = { version = "0.3", optional = false }
serde-wasm-bindgen = { version = "0.6", optional = false }
gloo-utils = "0.2"

[target.'cfg(target_os = "android")'.dependencies]
libc = "0.2"

[target.'cfg(not(any(target_arch = "wasm32", target_os = "android")))'.dependencies]
dioxus-desktop = "0.7.0-alpha.3"

[features]
default = []
web = []
android = []

[lib]
crate-type = ["cdylib", "rlib"]